### ISSUE TITLE
what means the max iteration of target empowerment model 

### ISSUE THREAD

**Issue by Usaywook** [ahq1993/inverse_rl#3]
code at ant_irl.py

```
    empw_model = Empowerment(env=env,fusion=True, max_itrs=4)
    t_empw_model = Empowerment(env=env,scope='t_efn',fusion=True, max_itrs=2, name='empowerment2')
```
but we do not call t_empw_model.fit(...)
why we set max_itrs=2 for target empowerment model?
where is the target empowerment model updated?

**Comment by ahq1993** [comment]
That must be a mistake, but you are right we do not use max_itrs for target model.
